#!/bin/sh

# Autostart
pgrep -x sxhkd > /dev/null || sxhkd &
polybar &
. ~/.config/bin/kbsetup.sh
xinput set-prop "SynPS/2 Synaptics TouchPad" "libinput Tapping Enabled" 1
xinput set-prop "SynPS/2 Synaptics TouchPad" "libinput Natural Scrolling Enabled" 1
feh --no-fehbg --bg-fill ~/wallpaper/default.png
dunst &
clipmenud &
xsetroot -cursor_name left_ptr
dunstify 'Welcome!'

# Workspaces
bspc monitor -d 1 2 3 4 5 6 7

# Config
bspc config border_width          2
bspc config window_gap            16
bspc config focus_follows_pointer true
bspc config pointer_modifier      super

bspc config normal_border_color   "#23252e"
bspc config active_border_color   "#23252e"
bspc config focused_border_color  "#7483C7"
bspc config presel_feedback_color "#7483C7"

bspc config split_ratio           0.5
bspc config borderless_monocle    true
bspc config gapless_monocle       false

bspc rule -a Conky:\* state=floating rectangle=200x600 sticky=off


